id: D90755F35
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-11-12T09:21:27+00:00'
last_modified: '2022-05-26T14:30:25.874847+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    66e4:
      image_group_id: I1PD95886
      title: ཞེན་ལོག་སྒྲོན་མ།
      total_pages: 1349
      order: 41
      base_file: 66e4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
