id: 1526e4ae323d420a8a4d898fe894b022
initial_creation_type: ocr
source_metadata:
  volumes:
    e89988855c074e68b80a7b74671ff37c:
      base_file: v041.txt
      image_group_id: I1PD95886
      title: ''
      total_pages: 1349
      volume_number: 41
